### PR TITLE
Add lua controlled tube

### PR DESCRIPTION
**Pull request by DS-Minetest**
The lua controlled tube is pretty similar to the luacontroller. Instead of A, B, C and D, the ports are blue, red, yellow, green, black and white. There's also a new event type called "item". It's called when an item passes the tube. The item will flow to the returned side or back.

### CODE REVIEW

**Comment by electrodude** [comment]
Forgive me for criticizing your idea without first reading the code or trying it out, but:

Can't you already do this by having a digiline chest (or a digiline detector tube feeding a normal chest) that notifies a Luacontroller of newly received items, which then commands one of several digiline filter-injectors adjacent to the chest to draw from the chest and send it on its way?

I don't like the idea of having many blocks that are all programmable in Lua.  I'd rather have a dumb block that speaks Digiline and have a luacontroller adjacent to it (or far away controlling other things too).  Making many blocks programmable in Lua is not only unorthogonal but also somewhat scary from a server security standpoint.  Maybe a Luacontroller API that other mods can use would help, but I feel like even that would go too much against orthogonality.

**Comment by raymoo** [comment]
@electrodude That would work nicely if it wasn't for minetest-mods/digilines#34. It can be worked around by using a digilines tube + a delay in the luacontroller, but it's not really ideal.

**Comment by DS-Minetest** [comment]
Ok, the PR is now ready to be reviewed or merged.

@electrodude The lua controlled tube works much more reliable. Complex constructions in minetest have very often the problem not to work because of missing reliability. This makes the lua_tube very useful. (And it can be turned off in the settings, so it shouldn't hurt anyone.)

**Comment by electrodude** [comment]
Since digiline chests are unreliable and the delay required to use a digiline detector tube is a pain, I have another proposal:

How about a digiline controlled redirector tube?  Matching items come out one special side, but unmatched items go straight through.  If you send it `default:dirt 23`, it will send the next 23 dirt blocks it gets out the match side, and send the rest straight through.  The filter's count decrements and finally disappears as items go through.  If it gets another message for the same item, it adds it to the one it already has.  It can handle multiple orders at once.

To use it as a replacement for a lua controlled tube, you have items go first through a digiline detector tube and then through a number of digiline redirector tubes.  A luacontroller listening to the digiline detector tube tells the digiline redirector tubes what to do, and they deal with the items when they get them.

This block would have other uses, like splitting many tubes multiplexed over a single tube.

**Comment by ForbiddenJ** [comment]
If this PR is merged, won't that mean this mod has to become LGPLv3 licensed?

**Comment by DS-Minetest** [comment]
I have added something to `LICENSE`, I thought that would be enough.

**Comment by raymoo** [comment]
I think only the affected file would need to be LGPL. Loading scripts is closer to dynamic linking than static linking.

**Pull request merged**
