### PR TITLE
add Digiline Filter-Injector

### PR DESCRIPTION
**Pull request by electrodude**
This adds a new type of Filter-Injector that waits for a digiline message on its channel and then pulls the items described by the message out of the inventory.  It is basically a Stackwise Injector that, on receiving a digiline message, sets its filter to the contents of the digiline message and then activates itself.  

Sending the message `{name="default:brick", count=2}` should do the same thing as setting the filter of a Stackwise Filter-Injector to two Brick Blocks and then punching it.

If no count is specified, it defaults to 1.  Since this is based off of the Stackwise Injector, it might make more sense if the default were an entire stack.  I can change this trivially.  

You can also send requests like `{{name="default:brick", count=1}, {name="default:dirt", count=1}}`, which acts the same as setting the filter to one Brick Block and one Dirt Block and then punching it.  

EDITED: If you send a string `"default:dirt"` instead of a table `{name="default:dirt"}`, the string is passed to `ItemStack` and the name and count are extracted from the resulting `ItemStack`.  You can also send a list of strings instead of tables: `{"default:dirt", "default:brick"}`, and the first item found will be pulled.

Punching this or activating it with Mesecons currently does nothing.  I'm not really sure what would be the right thing to do in either of those two cases, so I made it do nothing.  I guess I could make it use the previously-used filter, but I can't really see any usefulness in that.

The recipe is probably too cheap.  The darker of the two blue texture colors could probably be better.

### CODE REVIEW

**Comment by electrodude** [comment]
Not specifying a count is pulling a whole stack instead of just one item.  I'll fix it after it is decided which should happen when no count is specified.  If you think a whole stack would make more sense, then I should remove the broken code that's supposed to make it default to pulling only one item before you merge my code.

**Comment by HybridDog** [comment]
l didn't know that you can send tables via digiline, thanks.

**Comment by electrodude** [comment]
I forgot to implement a way to set the mode button...  Don't merge this yet.

I'm also interested in adding a Digiline Sorting Tube and a Digiline Detector Tube (send a digiline message containing a ItemStack string whenever an item enters it).  They'll both be in later PRs.  I'm mentioning these now because it would probably be best if they were implemented to work similarly and have similar interfaces.  Should I add them to this PR or to their own PRs?

For the Digiline Sorting Tube, I've modified the normal Sorting Tube to be configurable via Digilines.  I did this to the original Sorting Tube, instead of making a new, separate Digiline Sorting Tube.  The GUI is currently the same, except that it adds a `Channel` field if it detects that digilines is installed.  Sending it digiline messages changes its fake inventory.  Making the Digiline Sorting Tube a separate tube type might be better so it can be more expensive and so it can also conduct digiline messages, but then a digiline conductor pipe might also be a good idea.

Do you think it would make more sense to just modify the Itemwise and Stackwise Filter-Injectors to be also configurable via digilines instead of making a separate node?  If it's a separate node, it can be made more expensive, but then its interface will be inconsistent with that of the Digiline Sorting Tube.

**Comment by HybridDog** [comment]
>Do you think it would make more sense to just modify the Itemwise and Stackwise Filter-Injectors to be also configurable via digilines instead of making a separate node?

How about putting that microchip into an inventory slot of the injector to make digiline usage on the node possible?

btw: l noticed that more people answer my questions if l put them on the end of my text and avoid statements after the question mark. l'm still not sure about this.

**Comment by sofar** [comment]
This now conflicts and needs a rebase, plus you said to not merge. Do you have plans to address the issues you raised yourself?

**Comment by electrodude** [comment]
Sorry, I'll try to finish this next week.  I'll also make separate pull requests for the digiline detector tube and digiline sorting tube I made.  I think I'll keep this block as a separate block and I'll definitely keep the digiline detector tube as its own block, but I'm considering doing what @HybridDog recommended for the digiline sorting tube and just add a slot to the standard sorting tube that takes a special item to enable digilines interaction.


I never went through with this originally because I was thinking instead of doing it similarly to how the OpenPeripheral mod for Minecraft does things.  I was going to make a block that you put next to things that lets you interact with them via Digilines.  The things being interacted with wouldn't need to know anything about the digiline interface mod.  That worked well for Minecraft, since it was generally a pain to get people to make their blocks work as peripherals.  But this isn't really necessary for Minetest, since people seem generally to be pretty open to letting others add stuff to their own mods.  Also, it would probably be a headache to maintain if I did it that way.

**Comment by electrodude** [comment]
Sorry, I rebased it and then pushed it without really thinking.  I haven't tested it after the merge.  I'll tell you when it's actually ready.

**Comment by electrodude** [comment]
What should happen if you punch this block or give it a mesecon pulse?  Right now, doing that does nothing.  Should it remember its last filter (i.e. how it was configured by the last digiline message it received) and repeat it, or should it simply do nothing like it does now?

In other words, right now, this block is exactly the same as a Stackwise Filter-Injector whose inventory and buttons are configurable by digilines but otherwise has no actual GUI.  However, it doesn't remember its configuration between messages, and just reads it out of each digilines message it gets.  Should I make it remember all of its configuration after each message, so that punching it or giving it a mesecons pulse can activate it, or should I keep it how it is now?

Or, since the Digilines Filter-Injector is already somewhat overpowered, should I remove all of the fancy features of the other Filter-Injectors from the Digiline Filter-Injector and make it take just one ItemStack string and a flag for whether or not you want exact mode?

**Comment by sofar** [comment]
Maybe make mesecons toggle the device on-off entirely?

**Comment by electrodude** [comment]
But how would that be useful?  Someone who wanted that could just use the mesecons signal to control the luacontroller or whatever else it is that they have controlling the Digiline Filter-Injector.

**Comment by electrodude** [comment]
I think this is pretty much ready for merge.  I made the formspec look as much as I could like other formspecs from pipeworks, and I added the two buttons `Sequence slots by ...` and `Exact match - on/off` that are found on Stackwise Filter-Injectors, so that a luacontroller isn't necessary for initial setup if you just want to do something simple like control it via a Digiline Detector Tube (which I have working and I'll make a PR for after this is done).

If there is no digilines mod, the block is defined but has no crafting recipe and does not show up in creative inventory.  Having one in the world with no digilines didn't crash it for me.


It still doesn't respond to mesecons signals or do anything when punched.  I don't see the point in making mesecons disable it entirely - I would think a separate mesecons-controlled digiline gate block would be a better way to do that.  I could make mesecons signals enable/disable exact mode, but I can't really see how that's something you would ever want to change during operation, and there's a button in the GUI for it and you can send it `{exmatch = true/false, nofire=true}`.

**Comment by sofar** [comment]
Taking a brief look at this. Do you want your commits squashed or kept in order?

**Comment by sofar** [comment]
Maybe take out the .xcf files? I can do that when merging.

**Comment by electrodude** [comment]
I removed all of the .xcf files and an outdated comment.

Go ahead and squash all of my commits.

**Comment by HybridDog** [comment]
electrodude, if you haven't done it yet, you maybe could reduce the texture sizes using adv- and optipng

**Comment by electrodude** [comment]
I just tried it, optipng said they were all already optimized.  I guess I did it a while ago.

**Comment by HybridDog** [comment]
ok

**Comment by sofar** [comment]
649c7d79f6d70251d9da93ca1c648ca2d9cc5562

**Comment by electrodude** [comment]
Thanks!

**Pull request closed without merging**
