### PR TITLE
Nice settings

### PR DESCRIPTION
**Pull request by DS-Minetest**
This uses a `settingtypes.txt` file.

Doing it exactly like this makes not that much sense.

### CODE REVIEW

**Comment by DS-Minetest** [comment]
Should I put more effort into this PR to improve it (:+1: this comment)
or will it surely not be merged (:-1: this comment)?

**Comment by VanessaE** [comment]
If it makes things better, then of course (why would you opt not to?)

**Comment by DS-Minetest** [comment]
It's ready now to be reviewed (or merged).

While testing it, I recognized, that technic causes a crash if acceleration tube is deactivated, because there's no crafting recipe to be cleared. I should have written this instead in minetest-mods/technic/pull/339.

**Comment by VanessaE** [comment]
From a quick skim, it looks good.  @Ekdohibs ?

**Comment by Ekdohibs** [comment]
I quick look at it seems good.

**Comment by VanessaE** [comment]
Well, if it blows up, it's @DS-Minetest's fault now ;)

**Pull request merged**
