### PR TITLE
Do not register pipeworks:teleport_tube_1 if technic is enabled

### PR DESCRIPTION
**Pull request by Ryan-Nolan**
This prevents 'Unified Inventory' and other craft grids from displaying the overridden recipe
-Ignore previous pull request I thought a mod had to depend on mods that it wished to detect with minetest.get_modpath()

### CODE REVIEW

**Comment by VanessaE** [comment]
This is not the place to put this.  Rather, technic needs to properly "un-register" the recipes that it wants to override.  See https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2005-L2011.

**Comment by Ryan-Nolan** [comment]
im not sure that method actually works. thats the first thing I tried but it kept crashing with an error saying the input or output must be defined... I guess il have to maintain my own fork until technic/minetest_engine fix it

**Comment by Ryan-Nolan** [comment]
On another point. would it not be better to have pipeworks, change the recipe if technic is available(to the one technic currently defines) and remove the "override" from technic?

**Comment by VanessaE** [comment]
I think it's better to let technic do it.  If you're having problems with the recipe-clear function, you're surely Doing It Wrong.™  :smile:

**Comment by Ryan-Nolan** [comment]
maybe I am... I've literally gone off what little information the api.txt file and the wiki provides, this is what i used, it causes the server to crash with the error i mentioned above:

```
minetest.clear_craft({
	{ "homedecor:plastic_sheeting", "homedecor:plastic_sheeting", "homedecor:plastic_sheeting" },
	{ "default:desert_stone", "default:mese", "default:desert_stone" },
	{ "homedecor:plastic_sheeting", "homedecor:plastic_sheeting", "homedecor:plastic_sheeting" }
})

**Comment by VanessaE** [comment]
It says in the API to "use the same recipe table syntax", which would suggest to me that it should be written as:
```lua
minetest.clear_craft({
	recipe = {
		{ "homedecor:plastic_sheeting", "homedecor:plastic_sheeting", "homedecor:plastic_sheeting" },
		{ "default:desert_stone", "default:mese", "default:desert_stone" },
		{ "homedecor:plastic_sheeting", "homedecor:plastic_sheeting", "homedecor:plastic_sheeting" }
	}
})
```
...or using the output of the recipe as the key,
```lua
minetest.clear_craft({
	output = "pipeworks:teleport_tube_1"
})
```
Note that I haven't tried these, just giving my interpretation of the API.

**Pull request closed without merging**
