### PR TITLE
Autocrafter recipe

### PR DESCRIPTION
**Pull request by h-v-smacker**
The recipe uses some chimera for the plastic material: `basic_materials:plastic_sheeting`. It's plastic_sheet in basic_materials, and sheeting in homedecor.

### CODE REVIEW

**Comment by VanessaE** [comment]
Wrong repo again :smiley:   merged upstream

**Comment by h-v-smacker** [comment]
Well I pointed my git to gitlab as upstream and synchronize with it now, but i don't have a gitlab account, so i cannot make a PR there.

**Comment by VanessaE** [comment]
So make an account on gitlab, it takes very little time/effort.

**Comment by SmallJoker** [comment]
Sync.
f37b21e
https://gitlab.com/VanessaE/pipeworks/commit/f37b21e

**Pull request merged**
