### PR TITLE
update table.extend

### PR DESCRIPTION
**Pull request by HybridDog**

### CODE REVIEW

**Comment by Ekdohibs** [comment]
Hm, could you provide some benchmarks to show it is indeed faster?

**Comment by HybridDog** [comment]
```
local function f1(t1,t2)
	local tbl, tbl2 = table.copy(t1), table.copy(t2)
	local index = #tbl + 1
	for _, elt in ipairs(tbl2) do
		tbl[index] = elt
		index = index + 1
 	end
end

local function f2(t1, t2)
	local t1,t2 = table.copy(t1), table.copy(t2)
	local lt1 = #t1
	for i = 1,#t2 do
		t1[lt1 + i] = t2[i]
 	end
end


local function bt()
	local t1 = {}
	local t2 = {}
	for i = 1,100 do
		t1[i] = math.random()
		t2[i] = math.random()
	end
	local s = benchmark_function(f1, t1,t2)
	local g = benchmark_function(f2, t1,t2)
	print("bef", s)
	print("aft", g)
	--print(dump(f1(txt)) == dump(f2(txt)), s/g)
end

minetest.register_chatcommand("bt", {
	params = "a",
	description = "ahref",
	func = bt,
})
```
Note that due to the table.copys you can only see that the new one is faster but not how much it is faster.

>bef	45792.362622912
aft	48045.8798853
2016-07-16 10:11:26: ACTION[Server]: msg to singleplayer: "@#f3d2ff) (4.000215 s)@#ffffff)"
bef	45508.612582055
aft	46752.883117792
2016-07-16 10:11:45: ACTION[Server]: msg to singleplayer: "@#f3d2ff) (4.000137 s)@#ffffff)"
bef	46200.729479939
aft	48838.804644781
2016-07-16 10:12:00: ACTION[Server]: msg to singleplayer: "@#f3d2ff) (4.000258 s)@#ffffff)"

**Comment by t4im** [comment]
`ipairs` is usually a little slower than a numeric for-loop (one might argue, not enough to matter).

Keep in mind, `table.extend` isn't really extending the table, it concats sequential lists to each other.
Which raises the question: Wouldn't sequential list **merging** not be enough? Because that can perform a lot better in both cputime and memory allocation. Real table-extending too!

table-extend

**Comment by HybridDog** [comment]
The function returns nothing, it modifies t1, so you can't simply switch t1 and t2, can you?

**Comment by t4im** [comment]
List merging is indeed a different behavior compared to list concatenation. One way or another you'd have to get t1 *after* merging, either inline or through return. It also cannot guarantee order of elements.
Actual table-extension via `__index` behaves different too.

I do not recommend adding it to pipeworks; i just microbenchmarked it as an interesting related function, because i was microbenchmarking other stuff anyway.

The pr can clearly be merged as-is imo.

**Pull request closed without merging**
