### PR TITLE
Fix link to wiki documentation

### PR DESCRIPTION
**Pull request by Hawk777**

### CODE REVIEW

**Comment by VanessaE** [comment]
Please file this against the gitlab repo at https://gitlab.com/VanessaE/pipeworks

This repo here on Github is not official anymore.

**Comment by Hawk777** [comment]
Done. I had no idea that was the case; should it be mentioned somewhere that this repo is now unofficial?

**Comment by VanessaE** [comment]
I guess it should be, yeah.  Ironically, I can't do that :)

**Comment by VanessaE** [comment]
Gitlab PR merged.

**Pull request closed without merging**
